Repository astronomer/astronomer-cosmos, pull requests merged in 2023-03, with the labels that each got.

#166 [Databricks] Link Airflow task timeout with Databricks Notebook task
  cosmos/providers/databricks/notebook.py
  examples/databricks/example_databricks_workflow.py
  tests/databricks/test_notebook.py
Labels: provider/databricks

#163 Create retry buttons for Single task and full databricks jobs
  cosmos/providers/databricks/notebook.py
  cosmos/providers/databricks/plugin.py
  cosmos/providers/databricks/workflow.py
  docs/databricks/img/dbutils-notebook-success.png
  docs/databricks/img/repair-all-failed.png
  docs/databricks/img/repair-single-failed.png
  docs/databricks/workflows.rst
  pyproject.toml
  tests/conftest.py
  tests/databricks/test_notebook.py
  tests/databricks/test_plugin.py
Labels: provider/databricks

#86 Add OpenLineage to Cosmos
  cosmos/providers/dbt/core/operators.py
  cosmos/providers/dbt/parser/project.py
  docs/dbt/index.rst
  docs/dbt/lineage.rst
  pyproject.toml
Labels: enhancement, provider/dbt

#147 Move dbt root directory to dags folder
  cosmos/providers/dbt/core/operators.py
  cosmos/providers/dbt/core/utils/file_syncing.py
Labels: enhancement, provider/dbt

#195 Fix file lock check
  cosmos/providers/dbt/core/operators.py
  cosmos/providers/dbt/core/utils/file_syncing.py
Labels: bug

#196 Fix nox build_docs check
  docs/conf.py
  pyproject.toml
Labels: bug

#199 Add missing dependency to run docs locally
  docs/reference/_generated/cosmos.providers.dbt.DbtDag.rst
  docs/reference/_generated/cosmos.providers.dbt.DbtLSOperator.rst
  docs/reference/_generated/cosmos.providers.dbt.DbtRunOperationOperator.rst
  docs/reference/_generated/cosmos.providers.dbt.DbtRunOperator.rst
  docs/reference/_generated/cosmos.providers.dbt.DbtSeedOperator.rst
  docs/reference/_generated/cosmos.providers.dbt.DbtTaskGroup.rst
  docs/reference/_generated/cosmos.providers.dbt.DbtTestOperator.rst
  pyproject.toml
Labels: bug, documentation

#213 Add filelock as a dependency
  pyproject.toml
Labels: bug

#214 Make `shutil.copytree` call compatible with python3.7
  cosmos/providers/dbt/core/operators.py
Labels: bug

#216 Release 0.5.2
  cosmos/__init__.py
  cosmos/providers/dbt/core/operators.py
  pyproject.toml
Labels: release
