Repository astronomer/astronomer-cosmos, pull requests merged in 2023-02, with the labels that each got.

#114 fixes #106 update argument for dbt executable in docs
  docs/dbt/install-options.rst
Labels: documentation

#104 Add support for "Config" select/exclude to DbtDag & DbtTaskGroup parsers
  .pre-commit-config.yaml
  cosmos/providers/dbt/parser/project.py
  cosmos/providers/dbt/render.py
Labels: bug, enhancement

#119 Make `dag` arg optional for CosmosTaskGroup
  README.rst
  cosmos/core/airflow.py
  docs/dbt/index.rst
  docs/dbt/usage.rst
  docs/index.rst
  examples/dags/jaffle_shop.py
Labels: enhancement

#125 Create the 0.4.1 release
  .github/workflows/astro-deploy.yml
  README.rst
  astro_tests/dags/dbt_example_dags.py
  cosmos/__init__.py
  cosmos/core/airflow.py
  cosmos/providers/dbt/__init__.py
  cosmos/providers/dbt/core/utils/data_aware_scheduling.py
  cosmos/providers/dbt/render.py
  docs/dbt/index.rst
  docs/dbt/scheduling.rst
  docs/dbt/usage.rst
  docs/index.rst
  examples/dags/jaffle_shop.py
  examples/dags/load_dag_a.py
  examples/dags/load_dag_b.py
  tests/__init__.py
  tests/dbt/utils/test_data_aware_scheduling.py
  tests/validation_tests.py
Labels: enhancement

#129 Change cicd to use release branches instead of publishing from main
  .github/workflows/astro-deploy.yml
  astro_tests/Dockerfile
Labels: enhancement

#131 Add pre-commit badge
  README.rst
Labels: documentation, enhancement

#113 Issue 107
  cosmos/providers/dbt/core/profiles/databricks.py
  cosmos/providers/dbt/core/utils/profiles_generator.py
  tests/dbt/profiles_test.py
Labels: enhancement

#138 Remove unneeded dependencies from the extras
  pyproject.toml
Labels: enhancement

#137 Create docs connection configuration
  .gitignore
  docs/_static/connections_doc/bigquery_airflow_connection.png
  docs/_static/connections_doc/databricks_airflow_connection.png
  docs/_static/connections_doc/postgres_airflow_connection.png
  docs/_static/connections_doc/redshift_airflow_connection.png
  docs/_static/connections_doc/snowflake_airflow_connection.png
  docs/conf.py
  docs/dbt/connections.rst
  docs/dbt/index.rst
  pyproject.toml
Labels: documentation

#108 Databricks/databricks workflow taskgroup
  .gitignore
  cosmos/providers/databricks/__init__.py
  cosmos/providers/databricks/notebook.py
  cosmos/providers/databricks/workflow.py
  docs/databricks/workflows.rst
  examples/databricks/example_databricks_workflow.py
  pyproject.toml
  tests/conftest.py
  tests/databricks/__init__.py
  tests/databricks/test_notebook.py
  tests/databricks/test_workflow.py
Labels: enhancement

#162 [Databricks] Fix issue for using single notebook task launch without taskgroup
  cosmos/providers/databricks/constants.py
  cosmos/providers/databricks/notebook.py
  docs/databricks/workflows.rst
  examples/databricks/example_databricks_notebook.py
  tests/databricks/test_notebook.py
Labels: provider/databricks
