Repository astronomer/astronomer-cosmos, pull requests merged in 2023-01, with the labels that each got.

#78 Create the DbtDepsOperator
  cosmos/providers/dbt/core/operators.py
Labels: enhancement

#77 Refactor to support new features and code maintainability
  cosmos/__init__.py
  cosmos/core/airflow.py
  cosmos/core/graph/entities.py
  cosmos/core/parse/base_parser.py
  cosmos/core/render.py
  cosmos/providers/dbt/dag.py
  cosmos/providers/dbt/parser/jinja.py
  cosmos/providers/dbt/parser/project.py
  cosmos/providers/dbt/parser/utils.py
  cosmos/providers/dbt/render.py
  cosmos/providers/dbt/task_group.py
  docs/conf.py
  docs/dbt/configuration.rst
  docs/dbt/index.rst
  docs/dbt/install-options.rst
  docs/reference/_generated/cosmos.providers.dbt.DbtDag.rst
  docs/reference/_generated/cosmos.providers.dbt.DbtTaskGroup.rst
  docs/requirements.txt
  pyproject.toml
Labels: enhancement

#83 Convert cli commands to use dbt executable path
  cosmos/providers/dbt/core/operators.py
  cosmos/providers/dbt/render.py
  examples/Dockerfile
  examples/dags/attribution-playbook.py
  examples/dags/extract_dag.py
  examples/dags/jaffle_shop.py
  examples/dags/mrr-playbook.py
  examples/dbt/attribution-playbook/macros/drop_table.sql
  examples/dbt/jaffle_shop/macros/drop_table.sql
  examples/dbt/mrr-playbook/macros/drop_table.sql
Labels: enhancement, invalid

#88 Add support for python3.7
  cosmos/core/airflow.py
  cosmos/core/graph/entities.py
  cosmos/providers/dbt/core/operators.py
  cosmos/providers/dbt/dag.py
  cosmos/providers/dbt/parser/project.py
  cosmos/providers/dbt/render.py
  cosmos/providers/dbt/task_group.py
  pyproject.toml
Labels: bug, customer request

#96 Convert dbt_tags parameter to general select parameter
  cosmos/providers/dbt/dag.py
  cosmos/providers/dbt/render.py
  cosmos/providers/dbt/task_group.py
  docs/dbt/configuration.rst
  pyproject.toml
Labels: enhancement

#99 Add paths to select and exclude parameters for DbtDag & DbtTaskGroup
  cosmos/providers/dbt/render.py
Labels: enhancement, customer request

#103 Use targeted database for BigQuery profile
  cosmos/providers/dbt/core/utils/profiles_generator.py
Labels: enhancement

#100 Make region optional in Snowflake connection
  cosmos/providers/dbt/core/utils/profiles_generator.py
  pyproject.toml
  tests/dbt/profiles_test.py
Labels: bug, enhancement

#105 Add custom models directory argument
  cosmos/providers/dbt/dag.py
  cosmos/providers/dbt/parser/project.py
  cosmos/providers/dbt/render.py
  cosmos/providers/dbt/task_group.py
  docs/dbt/usage.rst
Labels: enhancement
