Repository astronomer/astronomer-cosmos, pull requests merged in 2024-12, with the labels that each got.

#1364 Enable kubernetes tests for dbt>=1.8
  .github/workflows/test.yml
  dev/Dockerfile.postgres_profile_docker_k8s
  scripts/test/kubernetes-setup.sh
Labels: execution:kubernetes, area:testing, size:S, lgtm

#1370 Remove dependency `eval_type_backport`
  pyproject.toml
Labels: area:dependencies, size:XS

#1371 Remove 'dbt-core<1.8.9' pin
  pyproject.toml
  scripts/test/integration-setup.sh
Labels: area:dependencies, size:XS

#1372 Add support for the "at" operator
  cosmos/dbt/selector.py
  docs/configuration/selecting-excluding.rst
  tests/dbt/test_selector.py
Labels: area:selector, size:L, lgtm

#1366 Refactor `dbt-sqlite` tests to use `dbt-postgres`
  .github/workflows/test.yml
  .pre-commit-config.yaml
  dev/dags/dbt/jaffle_shop/models/exposures.yml
  dev/dags/dbt/jaffle_shop/models/orders.sql
  dev/dags/dbt/jaffle_shop/models/ｍｕｌｔｉｂｙｔｅ.sql
  dev/dags/dbt/jaffle_shop/profiles.yml
  dev/dags/dbt/jaffle_shop/target/manifest.json
  dev/dags/dbt/simple/.gitignore
  dev/dags/dbt/simple/README.md
  dev/dags/dbt/simple/analyses/.gitkeep
  dev/dags/dbt/simple/convert_csv_to_db.py
  dev/dags/dbt/simple/dbt_project.yml
  dev/dags/dbt/simple/macros/.gitkeep
  dev/dags/dbt/simple/models/movies_ratings_simplified.sql
  dev/dags/dbt/simple/models/source.yml
  dev/dags/dbt/simple/models/top_animations.sql
  dev/dags/dbt/simple/profiles.yml
  dev/dags/dbt/simple/seeds/.gitkeep
  dev/dags/dbt/simple/snapshots/.gitkeep
  dev/dags/dbt/simple/tests/.gitkeep
  dev/dags/example_cosmos_sources.py
  pyproject.toml
  scripts/test/integration-sqlite-setup.sh
  scripts/test/integration-sqlite.sh
  scripts/test/integration.sh
  tests/dbt/test_graph.py
  tests/operators/test_local.py
  tests/sample/manifest_source.json
  tests/test_example_dags.py
  tests/test_example_dags_no_connections.py
Labels: profile:postgres, area:config, area:testing, area:ci, size:L, lgtm

#1376 Pin dbt-databricks version to < 1.9
  pyproject.toml
  scripts/test/integration-setup.sh
Labels: area:dependencies, area:ci, size:XS, lgtm

#1381 Remove typing-extensions as dependency
  pyproject.toml
Labels: area:dependencies, size:XS

#1383 Remove Pytest durations from tests scripts
  scripts/test/integration-dbt-1-5-4.sh
  scripts/test/integration-expensive.sh
  scripts/test/integration-kubernetes.sh
  scripts/test/integration.sh
  scripts/test/unit-cov.sh
  scripts/test/unit.sh
Labels: area:testing, size:XS

#1377 Add support to `TestBehavior.BUILD`
  cosmos/airflow/graph.py
  cosmos/constants.py
  dev/dags/example_cosmos_dbt_build.py
  docs/_static/test_behavior_after_all.png
  docs/_static/test_behavior_after_each.png
  docs/_static/test_behavior_build.png
  docs/configuration/testing-behavior.rst
  tests/airflow/test_graph.py
Labels: area:performance, area:rendering, dbt:build, size:L, lgtm

#1389 Add helper functions for uploading target directory artifacts to remote cloud storages
  cosmos/constants.py
  cosmos/io.py
  cosmos/operators/local.py
  dev/dags/cosmos_callback_dag.py
  dev/dags/example_operators.py
  docs/configuration/callbacks.rst
  docs/configuration/index.rst
  tests/test_example_dags.py
  tests/test_io.py
Labels: execution:local, size:XL, lgtm, execution:callback

#1396 Fix releasing package to PyPI
  .github/workflows/deploy.yml
Labels: area:ci, size:XS

#1403 Increase performance tests models
  .github/workflows/test.yml
Labels: area:performance, area:ci, size:XS

#1401 Mention in documentation that the callback functionality is supported in ExecutionMode.VIRTUALENV
  dev/dags/example_virtualenv.py
  docs/configuration/callbacks.rst
Labels: area:execution, area:docs, size:S, lgtm

#1362 Save tasks map as DbtToAirflowConverter property
  cosmos/airflow/graph.py
  cosmos/converter.py
  dev/dags/example_tasks_map.py
  docs/configuration/dag-customization.rst
  docs/configuration/index.rst
  tests/test_converter.py
Labels: area:rendering, size:L, lgtm

#1385 Add security policy
  README.rst
  SECURITY.rst
  docs/index.rst
Labels: area:docs, size:L

#1405 Fix source resource type tests
  dev/dags/dbt/altered_jaffle_shop/dbt_project.yml
  dev/dags/dbt/altered_jaffle_shop/models/orders.sql
  dev/dags/example_cosmos_dbt_build.py
  dev/dags/example_source_rendering.py
  tests/dbt/test_graph.py
  tests/sample/manifest_source.json
Labels: area:testing, size:M, lgtm

#1409 Unpin dbt-databricks version
  pyproject.toml
  scripts/test/integration-setup.sh
Labels: profile:databricks, area:dependencies, size:XS

#1406 Fix Snowflake Profile mapping when using AWS default region
  cosmos/profiles/snowflake/base.py
  cosmos/profiles/snowflake/user_encrypted_privatekey_env_variable.py
  cosmos/profiles/snowflake/user_encrypted_privatekey_file.py
  cosmos/profiles/snowflake/user_pass.py
  cosmos/profiles/snowflake/user_privatekey.py
  tests/profiles/snowflake/test_snowflake_base.py
Labels: profile:snowflake, size:L

#1390 Add logging of stdout to dbt graph run_command.
  cosmos/dbt/graph.py
  tests/dbt/test_graph.py
Labels: area:logging, size:XS, lgtm

#1411 Drop running 1000 models in the CI
  .github/workflows/test.yml
Labels: area:ci, size:XS, lgtm

#1404 Add Oracle Profile mapping
  cosmos/profiles/__init__.py
  cosmos/profiles/oracle/__init__.py
  cosmos/profiles/oracle/user_pass.py
  pyproject.toml
  tests/profiles/oracle/test_oracle_user_pass.py
Labels: area:profile, size:L, lgtm

#1400 Add warning callback on source freshness
  cosmos/airflow/graph.py
  cosmos/dbt/parser/output.py
  cosmos/operators/local.py
  dev/dags/example_source_rendering.py
  docs/configuration/source-nodes-rendering.rst
  tests/dbt/parser/test_output.py
  tests/operators/test_local.py
Labels: dbt:source, size:L, lgtm

#1278 Support rendering tasks with non-ASCII characters
  cosmos/airflow/graph.py
  cosmos/config.py
  docs/configuration/index.rst
  docs/configuration/render-config.rst
  docs/configuration/task-display-name.rst
  tests/airflow/test_graph.py
Labels: area:rendering, size:L

#1360 Fix dag randering for taskflow + DbtTaskGroup combo
  cosmos/converter.py
  dev/dags/example_taskflow.py
Labels: area:rendering, size:M

#1347 adds profile_config for Docker
  cosmos/operators/docker.py
  tests/test_converter.py
Labels: area:execution, area:profile, size:S

#1413 Address review comments on PR 1347 regarding profile_config for ExecutionMode.Docker
  cosmos/operators/docker.py
  docs/getting_started/docker.rst
  tests/operators/test_docker.py
Labels: execution:docker, area:profile, size:M, lgtm

#1415 Support rendering build operator task-id with non-ASCII characters
  cosmos/airflow/graph.py
  tests/airflow/test_graph.py
Labels: area:rendering, size:M, lgtm

#1397 Emit telemetry to Scarf during DAG run
  PRIVACY_NOTICE.rst
  README.rst
  cosmos/constants.py
  cosmos/listeners/__init__.py
  cosmos/listeners/dag_run_listener.py
  cosmos/plugin/__init__.py
  cosmos/settings.py
  cosmos/telemetry.py
  docs/index.rst
  tests/listeners/test_dag_run_listener.py
  tests/test_telemetry.py
Labels: area:config, area:docs, size:L

#1395 Release 1.8.0
  CHANGELOG.rst
  cosmos/__init__.py
Labels: area:logging, area:dependencies, area:rendering, size:M

#1422 Add `kwargs` param in DocsOperator method upload_to_cloud_storage
  CHANGELOG.rst
  cosmos/__init__.py
  cosmos/operators/local.py
Labels: size:S

#1414 Remove unused docs dependency
  docs/requirements.txt
  pyproject.toml
Labels: area:dependencies, size:S, lgtm

#1432 Install providers with airflow
  scripts/test/pre-install-airflow.sh
Labels: size:XS, lgtm

#1428 Enable Docs DAG in CI leveraging existing CI connections
  dev/dags/dbt_docs.py
Labels: area:ci, size:M, lgtm

#1433 Fix rendering dbt tests with multiple parents
  cosmos/airflow/graph.py
  dev/dags/dbt/jaffle_shop/models/schema.yml
  dev/dags/dbt/multiple_parents_test/dbt_project.yml
  dev/dags/dbt/multiple_parents_test/macros/custom_test_combined_model.sql
  dev/dags/dbt/multiple_parents_test/models/combined_model.sql
  dev/dags/dbt/multiple_parents_test/models/model_a.sql
  dev/dags/dbt/multiple_parents_test/models/model_b.sql
  dev/dags/dbt/multiple_parents_test/models/schema.yml
  dev/dags/dbt/multiple_parents_test/profiles.yml
  dev/dags/example_tests_multiple_parents.py
  tests/dbt/parser/test_project.py
  tests/dbt/test_graph.py
  tests/test_converter.py
Labels: area:rendering, dbt:test, size:L

#1436 Release 1.8.1
  CHANGELOG.rst
  cosmos/__init__.py
Labels: area:rendering, area:lineage, area:ci, size:S, lgtm

#1437 Docs: Fix broken links and rendering
  README.rst
  docs/configuration/scheduling.rst
  docs/getting_started/azure-container-instance.rst
  docs/getting_started/index.rst
Labels: area:docs, size:XS
