Repository astronomer/astronomer-cosmos, pull requests merged in 2024-10, with the labels that each got.

#1200 Create single virtualenv when `DbtVirtualenvBaseOperator` has `virtualenv_dir=None` and `is_virtualenv_dir_temporary=True`
  cosmos/operators/virtualenv.py
  tests/operators/test_virtualenv.py
Labels: area:performance, execution:virtualenv, area:execution, size:L, lgtm

#1237 Update GCP manifest file path based on new secret update
  dev/dags/cosmos_manifest_example.py
Labels: area:ci, size:XS, lgtm

#1241 Refactor docs for async mode execution
  docs/configuration/scheduling.rst
  docs/getting_started/execution-modes.rst
Labels: area:docs, size:S, lgtm

#1240 Fix Dataset and DatasetAlias scheduling in Airflow 2.10
  cosmos/dataset.py
  docs/configuration/scheduling.rst
  tests/test_dataset.py
  tests/test_example_dags.py
Labels: area:datasets, size:L, lgtm

#1234 Release 1.7
  CHANGELOG.rst
  cosmos/__init__.py
Labels: area:execution, area:datasets, area:docs, area:ci, size:M, lgtm

#1250 Improve dbt Docs Hosting Debugging -- Update dbt_docs_not_set_up.html
  cosmos/plugin/templates/dbt_docs_not_set_up.html
Labels: dbt:docs, size:XS, lgtm, area:plugin

#1255 fix: Replace login by user for clickhouse profile
  cosmos/profiles/clickhouse/user_pass.py
  tests/profiles/clickhouse/test_clickhouse_userpass.py
Labels: profile:clickhouse, size:S, lgtm

#1256 [DOCS]: Add dedicated scarf tracking pixel to readme
  README.rst
Labels: area:docs, size:XS, lgtm

#1251 [DOCS]: Adds Welcome Section and "What Is Cosmos" Blurb to Home Page
  docs/_static/jaffle_shop_dbt_graph.png
  docs/index.rst
Labels: area:docs, size:M, lgtm

#1275 Update issue template bug.yml - cosmos version update in the dropdown
  .github/ISSUE_TEMPLATE/01-bug.yml
Labels: area:config, size:S, lgtm

#1283 Update the URL for sample dbt docs hosted in Astronomer S3 bucket
  dev/docker-compose.yaml
  docs/configuration/generating-docs.rst
Labels: area:docs, dbt:docs, size:XS, lgtm

#1280 Fix displaying dbt docs as menu item in Astro
  CHANGELOG.rst
  cosmos/__init__.py
  cosmos/plugin/__init__.py
  tests/plugin/test_plugin.py
Labels: area:testing, size:M, lgtm, area:plugin

#1252 Fix DbtVirtualenvBaseOperator to use correct virtualenv Python path
  cosmos/operators/local.py
  cosmos/operators/virtualenv.py
  tests/operators/test_local.py
Labels: area:execution, area:testing, size:M, lgtm

#1286 Minor refactor on `VirtualenvOperators` & add test for PR #1253 &
  cosmos/operators/virtualenv.py
  dev/dags/example_virtualenv_mini.py
  tests/operators/test_virtualenv.py
Labels: area:execution, area:testing, size:M, lgtm

#1287 Release 1.7.1
  CHANGELOG.rst
  cosmos/__init__.py
Labels: profile:clickhouse, execution:virtualenv, area:docs, size:S, lgtm

#1288 Add stalebot to label/close stale PRs and issues
  .github/workflows/stale.yml
Labels: area:ci, size:S, lgtm

#1294 Fix Netlify build timeouts
  docs/requirements.txt
  netlify.toml
Labels: area:dependencies, size:S, lgtm

#1296 Fix parsing dbt ls outputs that contain JSONs that are not dbt nodes
  cosmos/dbt/graph.py
  tests/dbt/test_graph.py
Labels: bug, parsing:dbt_ls, size:M, lgtm

#1298 Fix security vulnerability, by not pinning Airflow 2.10.0
  docs/requirements.txt
Labels: area:dependencies, size:XS, lgtm
