Repository astronomer/astronomer-cosmos, pull requests merged in 2024-03, with the labels that each got.

#864 Release 1.4.0a1
  CHANGELOG.rst
  cosmos/__init__.py
Labels: profile:databricks, parsing:dbt_ls, execution:local, area:execution, dbt:docs, size:M, lgtm

#876 Improve dbt docs plugin rendering padding
  cosmos/plugin/__init__.py
Labels: size:XS

#874 Update docs regarding docs plugin in Astronomer cloud
  docs/configuration/hosting-docs.rst
Labels: execution:local, area:docs, size:S, lgtm

#887 Update pip install instructions in docs
  docs/contributing.rst
Labels: execution:kubernetes, area:docs, size:XS, lgtm

#886 Expose the dbt graph in the `DbtToAirflowConverter` class
  cosmos/converter.py
  tests/test_converter.py
Labels: parsing:custom, area:parsing, size:M, lgtm

#883 [Bugfix] Dbt docs operator should not look for `graph.gpickle` file when `--no-write-json` is passed.
  cosmos/operators/local.py
  tests/operators/test_local.py
Labels: execution:local, area:execution, dbt:docs, size:S, lgtm

#900 Replace deprecated DummyOperator by EmptyOperator if Airflow >=2.4.0
  dev/dags/example_cosmos_sources.py
Labels: area:dependencies, area:rendering, area:testing, size:S, lgtm

#899 Enable `append_env` in `operator_args` by default
  cosmos/operators/base.py
  tests/operators/test_azure_container_instance.py
  tests/operators/test_docker.py
  tests/operators/test_kubernetes.py
  tests/operators/test_local.py
Labels: parsing:custom, execution:docker, area:parsing, dbt:parse, size:S, lgtm

#872 Fix ACI integration
  cosmos/operators/azure_container_instance.py
  tests/operators/test_azure_container_instance.py
Labels: execution:docker, area:execution, size:M, lgtm
