Repository astronomer/astronomer-cosmos, pull requests merged in 2025-03, with the labels that each got.

#1580 feat: implement exclude resource type
  cosmos/dbt/selector.py
  docs/configuration/selecting-excluding.rst
  tests/dbt/test_selector.py
Labels: area:selector, area:docs, area:testing, size:M, lgtm

#1543 Fix dbt project parsing `dbt_vars` behavior
  cosmos/dbt/graph.py
  tests/dbt/test_graph.py
Labels: area:rendering, area:testing, size:M, lgtm

#1586 Update the GH bug issue template
  .github/ISSUE_TEMPLATE/01-bug.yml
Labels: size:XS

#1588 Fix the async execution mode read sql files for dbt packages
  cosmos/__init__.py
  cosmos/airflow/graph.py
  cosmos/dbt/graph.py
  cosmos/operators/local.py
  tests/airflow/test_graph.py
  tests/dbt/test_graph.py
  tests/operators/test_local.py
Labels: area:execution, dbt:run, size:M, lgtm

#1597 Improve BQ async error handling
  cosmos/operators/_asynchronous/bigquery.py
Labels: profile:bigquery, size:S

#1601 Fix path selector when `manifest.json` was created in MS Windows
  cosmos/dbt/graph.py
  tests/dbt/test_graph.py
Labels: customer request, parsing:dbt_manifest, area:selector, size:S

#1603 Fix log that prints 'Total filtered nodes'
  cosmos/dbt/graph.py
Labels: area:logging, size:XS

#1602 Fix select behaviour using `LoadMode.MANIFEST` and a path with star
  cosmos/dbt/selector.py
  tests/dbt/test_selector.py
Labels: customer request, parsing:dbt_manifest, area:selector, size:S

#1599 Run async in CI DAG without setup/teardown task
  cosmos/operators/_asynchronous/bigquery.py
  cosmos/operators/local.py
  tests/operators/_asynchronous/test_bigquery.py
  tests/operators/test_local.py
  tests/test_example_dags.py
Labels: profile:bigquery, area:execution, area:testing, size:M, lgtm

#1604 Add test case that fully covers recent select issue
  tests/dbt/test_graph.py
  tests/sample/small_manifest.json
Labels: area:selector, area:testing, size:M

#1535 Add CI job to test multiple dbt versions for the async DAG
  .github/workflows/test.yml
  dev/dags/simple_dag_async.py
  pyproject.toml
  scripts/test/integration-dbt-async.sh
  scripts/test/integration.sh
  scripts/test/performance.sh
  scripts/test/unit-cov.sh
  scripts/test/unit.sh
  tests/test_async_example_dag.py
Labels: area:testing, area:ci, size:L, lgtm

#1600 Improve unit tests speed from 89s to 14s
  cosmos/io.py
  tests/dbt/test_graph.py
  tests/operators/test_local.py
  tests/test_io.py
Labels: area:testing, size:M

#1592 fix: container_name is null for ecs integration
  cosmos/operators/aws_ecs.py
  tests/operators/test_aws_ecs.py
Labels: area:execution, size:XS, lgtm

#1612 Release 1.9.1 changelog
  CHANGELOG.rst
  cosmos/__init__.py
Labels: area:docs, area:ci, size:M

#1614 Update contributing.rst to latest test matrix
  docs/contributing.rst
Labels: area:docs, size:S

#1616 Detach dbt vars used to render DAGs from the operator args'
  cosmos/converter.py
  docs/configuration/operator-args.rst
  tests/test_converter.py
Labels: area:rendering, size:M

#1617 Support filtering by config meta nested properties
  cosmos/dbt/selector.py
  docs/configuration/selecting-excluding.rst
  tests/dbt/test_selector.py
Labels: parsing:dbt_manifest, area:selector, size:L

#1624 Release 1.9.2
  .pre-commit-config.yaml
  CHANGELOG.rst
  cosmos/__init__.py
  cosmos/converter.py
  cosmos/dbt/selector.py
  docs/configuration/operator-args.rst
  docs/configuration/selecting-excluding.rst
  docs/contributing.rst
  tests/dbt/test_selector.py
  tests/test_converter.py
Labels: area:config, area:docs, area:testing, size:L

#1626 Release 1.9.2 (add changelog and version bump)
  CHANGELOG.rst
  cosmos/__init__.py
Labels: area:rendering, size:S

#1627 Add dev tool for airflow3
  scripts/airflow3/README.md
  scripts/airflow3/dags/hello.py
  scripts/airflow3/env.sh
  scripts/airflow3/requirements.txt
  scripts/airflow3/setup.sh
  scripts/airflow3/tests.sh
Labels: area:config, size:L, lgtm

#1642 Run cosmos operator in Airflow3
  cosmos/constants.py
  cosmos/operators/local.py
  scripts/airflow3/dags/example_operators.py
  scripts/airflow3/env.sh
  scripts/airflow3/setup.sh
  tests/operators/test_local.py
Labels: execution:local, size:L, lgtm
