Repository astronomer/astronomer-cosmos, pull requests merged in 2025-04, with the labels that each got.

#1656 Improve AF3 tooling
  cosmos/operators/base.py
  scripts/airflow3/README.md
  scripts/airflow3/env.sh
  scripts/airflow3/requirements.txt
  scripts/airflow3/setup.sh
Labels: area:dependencies, size:M, lgtm

#1657 Support rendering DbtDag in Airflow 3
  cosmos/core/airflow.py
  cosmos/operators/_asynchronous/databricks.py
  cosmos/operators/local.py
  scripts/airflow3/dags/basic_cosmos_dag.py
Labels: area:rendering, size:M

#1658 Add .gitignore file for the scripts/airflow3 directory
  scripts/airflow3/.gitignore
Labels: size:XS, lgtm

#1662 Skip associating 'openlineage_events_completes' to 'ti' in AF3
  cosmos/operators/local.py
Labels: area:lineage, size:XS, lgtm

#1660 Install Airflow from main branch
  scripts/airflow3/README.md
  scripts/airflow3/env.sh
  scripts/airflow3/install_from_main.sh
Labels: size:M

#1665 Check only major version until AF3 stable release
  cosmos/constants.py
  cosmos/operators/local.py
Labels: size:S

#1661 Refactor Rendered Task Instance Fields (RTIF) handling for Airflow 2.x and 3.x
  cosmos/operators/local.py
  tests/operators/test_local.py
  tests/operators/test_virtualenv.py
Labels: area:rendering, area:testing, size:L, lgtm

#1663 Fix `test_indirect_selection` flag to be propagated in case of `TestBehavior.BUILD`
  cosmos/airflow/graph.py
  tests/airflow/test_graph.py
Labels: area:selector, dbt:build, size:M, lgtm

#1668 Support running `dbt deps` incrementally to pre-defined `dbt_packages` during DAG parsing
  cosmos/config.py
  cosmos/constants.py
  cosmos/dbt/graph.py
  cosmos/dbt/project.py
  cosmos/settings.py
  dev/dags/example_dbt_deps.py
  tests/dbt/test_project.py
Labels: area:parsing, dbt:deps, size:L

#1670 Support running `dbt deps` incrementally to pre-defined `dbt_packages` during task execution
  cosmos/converter.py
  cosmos/operators/local.py
  tests/operators/test_local.py
Labels: execution:local, area:config, dbt:deps, size:M

#1675 Add symlink to basic_cosmos_task_group DAG for Airflow 3 dags setup
  dev/dags/basic_cosmos_task_group.py
  scripts/airflow3/dags/basic_cosmos_task_group.py
  scripts/airflow3/env.sh
Labels: size:XS

#1671 Add documentation related to `copy_dbt_packages` configurations
  cosmos/config.py
  cosmos/operators/local.py
  cosmos/settings.py
  docs/configuration/cosmos-conf.rst
  docs/configuration/operator-args.rst
  docs/configuration/project-config.rst
Labels: area:config, area:docs, size:S

#1674 Add Airflow 3 compatibility for BiqQuery deferrable support (ExecutionMode.AIRFLOW_ASYNC)
  cosmos/operators/_asynchronous/bigquery.py
  dev/dags/simple_dag_async.py
  scripts/airflow3/dags/simple_dag_async.py
  scripts/airflow3/env.sh
  scripts/airflow3/requirements.txt
  tests/operators/_asynchronous/test_bigquery.py
Labels: area:dependencies, area:execution, size:M, lgtm

#1676 Remove original_jaffle_shop dbt project
  dev/dags/dbt/original_jaffle_shop/.gitignore
  dev/dags/dbt/original_jaffle_shop/LICENSE
  dev/dags/dbt/original_jaffle_shop/README.md
  dev/dags/dbt/original_jaffle_shop/dbt_ls_models_staging.txt
  dev/dags/dbt/original_jaffle_shop/dbt_project.yml
  dev/dags/dbt/original_jaffle_shop/macros/drop_table.sql
  dev/dags/dbt/original_jaffle_shop/models/customers.sql
  dev/dags/dbt/original_jaffle_shop/models/docs.md
  dev/dags/dbt/original_jaffle_shop/models/orders.sql
  dev/dags/dbt/original_jaffle_shop/models/overview.md
  dev/dags/dbt/original_jaffle_shop/models/schema.yml
  dev/dags/dbt/original_jaffle_shop/models/staging/schema.yml
  dev/dags/dbt/original_jaffle_shop/models/staging/stg_customers.sql
  dev/dags/dbt/original_jaffle_shop/models/staging/stg_orders.sql
  dev/dags/dbt/original_jaffle_shop/models/staging/stg_payments.sql
  dev/dags/dbt/original_jaffle_shop/profiles.yml
  dev/dags/dbt/original_jaffle_shop/seeds/raw_customers.csv
  dev/dags/dbt/original_jaffle_shop/seeds/raw_orders.csv
  dev/dags/dbt/original_jaffle_shop/seeds/raw_payments.csv
  dev/dags/simple_dag_async.py
  tests/operators/test_airflow_async.py
Labels: area:execution, size:L, lgtm

#1684 Fix Variable not found issue in Airflow 3
  cosmos/dbt/graph.py
Labels: area:parsing, size:S

#1697 Make wording and command consistent in the contributing doc
  docs/contributing.rst
Labels: area:docs, size:S, lgtm

#1692 Disable CosmosPlugin for AF3
  cosmos/plugin/__init__.py
  cosmos/plugin/plugin_impl.py
  docs/configuration/generating-docs.rst
  docs/configuration/hosting-docs.rst
  tests/plugin/test_plugin.py
Labels: area:docs, size:XL, lgtm, area:plugin

#1696 Enable running setup/teardown task
  scripts/airflow3/env.sh
  scripts/airflow3/requirements.txt
Labels: size:S, lgtm

#1700 Fix outdated echo in AF3 tool
  scripts/airflow3/setup.sh
Labels: size:XS

#1701 Use `schedule` param in example DAGs instead of 2.10 deprecated and 3.0 removed `schedule_interval`
  dev/dags/basic_cosmos_dag.py
  dev/dags/basic_cosmos_task_group_different_owners.py
  dev/dags/cosmos_callback_dag.py
  dev/dags/cosmos_manifest_example.py
  dev/dags/cosmos_profile_mapping.py
  dev/dags/cosmos_seed_dag.py
  dev/dags/dbt_docs.py
  dev/dags/example_cosmos_cleanup_dag.py
  dev/dags/example_cosmos_dbt_build.py
  dev/dags/example_cosmos_python_models.py
  dev/dags/example_cosmos_sources.py
  dev/dags/example_dbt_deps.py
  dev/dags/example_model_version.py
  dev/dags/example_source_rendering.py
  dev/dags/example_task_mapping.py
  dev/dags/example_taskflow.py
  dev/dags/example_tasks_map.py
  dev/dags/performance_dag.py
  dev/dags/user_defined_profile.py
  tests/operators/test_airflow_async.py
Labels: size:M

#1553 feature: Add DuckDB profile mapping
  cosmos/profiles/__init__.py
  cosmos/profiles/duckdb/__init__.py
  cosmos/profiles/duckdb/user_pass.py
  dev/dags/example_duckdb_dag.py
  pyproject.toml
  tests/profiles/duckdb/test_duckdb_user_pass.py
Labels: area:profile, area:testing, size:L, lgtm

#1699 Enable integration tests for the DuckDB adaptor (PR #1553)
  .github/workflows/test.yml
  cosmos/profiles/__init__.py
  cosmos/profiles/duckdb/user_pass.py
  dev/dags/example_duckdb_dag.py
  pyproject.toml
  scripts/test/integration-dbt-1-5-4.sh
  scripts/test/integration-setup.sh
  tests/profiles/duckdb/test_duckdb_user_pass.py
  tests/test_example_dags.py
  tests/test_example_dags_no_connections.py
Labels: area:testing, area:ci, size:M, lgtm

#1680 Allowing for correct name in select clause in the case of detached tests
  cosmos/airflow/graph.py
  tests/test_converter.py
Labels: area:selector, dbt:test, size:XS, lgtm

#1695 add MonteCarlo callback example in documentation for importing dbt artifacts
  docs/configuration/callbacks.rst
Labels: area:docs, size:M, lgtm

#1698 Set CosmosPlugin to None for airflow 3
  cosmos/plugin/__init__.py
  tests/plugin/test_plugin.py
  tests/plugin/test_plugin_af3.py
Labels: size:M, lgtm, area:plugin

#1714 Use a different way to get tasks count for asserting test_perf_dag
  .github/workflows/test.yml
  tests/perf/test_performance.py
Labels: area:testing, size:XS, lgtm

#1715 Reinstall airflow dependency on pydantic>=2.11 for dbt adapater versions 1.6 & 1.9
  .github/workflows/test.yml
  scripts/test/integration-dbt-async.sh
Labels: area:dependencies, size:S, lgtm

#1723 Add files not needed for git tracking to .gitignore
  .gitignore
Labels: size:XS, lgtm

#1719 Use latest minor versions for dbt adapters to get in compatibility fixes
  .github/workflows/test.yml
  scripts/test/integration-dbt-async.sh
Labels: area:dependencies, area:ci, size:M, lgtm

#1724 Ensure virtualenv_dir path exists
  cosmos/operators/virtualenv.py
  tests/operators/test_virtualenv.py
Labels: execution:virtualenv, size:XS, lgtm

#1725 Fix Airflow 3 tests raising `generate_run_id() takes 0 positional arguments`
  tests/operators/test_local.py
  tests/test_example_dags.py
  tests/test_example_k8s_dags.py
  tests/utils.py
Labels: area:testing, size:M

#1716 Fix dataset tests failing in Airflow 3
  tests/operators/test_local.py
Labels: area:datasets, area:testing, size:S

#1726 Enable example DAGs to run in CI that were disabled in PR #1646
  dev/dags/basic_cosmos_task_group.py
  dev/dags/basic_cosmos_task_group_different_owners.py
  dev/dags/cosmos_manifest_example.py
  dev/dags/cosmos_profile_mapping.py
  dev/dags/example_cosmos_cleanup_dag.py
  dev/dags/example_taskflow.py
  dev/dags/user_defined_profile.py
  tests/test_example_dags.py
Labels: area:testing, area:ci, size:M, lgtm

#1681 Refactor kubernetes warning callback handling
  cosmos/operators/kubernetes.py
  pyproject.toml
  tests/operators/test_kubernetes.py
Labels: execution:kubernetes, size:XL

#1713 Support emitting Assets with Airflow 3
  cosmos/operators/local.py
  tests/operators/test_local.py
Labels: execution:local, area:datasets, area:testing, size:L

#1732 docs: Change async feature to be non-experimental
  docs/getting_started/execution-modes.rst
Labels: area:docs, size:S
