Repository astronomer/astronomer-cosmos, pull requests merged in 2025-05, with the labels that each got.

#1729 Improve dataset/asset driven scheduling documentation
  docs/airflow3_compatibility/index.rst
  docs/configuration/cosmos-conf.rst
  docs/configuration/scheduling.rst
Labels: area:datasets, area:docs, size:M

#1672 Release 1.10.0
  CHANGELOG.rst
  cosmos/__init__.py
  cosmos/operators/local.py
  cosmos/settings.py
  tests/operators/test_local.py
  tests/utils.py
Labels: area:execution, area:datasets, dbt:deps, area:testing, size:L, area:plugin

#1742 Fix the docs rendering
  docs/configuration/cosmos-conf.rst
Labels: area:rendering, area:docs, size:XS

#1737 Add sqlserver profile mapping
  cosmos/profiles/__init__.py
  cosmos/profiles/sqlserver/__init__.py
  cosmos/profiles/sqlserver/standard_sqlserver_auth.py
  pyproject.toml
  tests/profiles/sqlserver/test_standard_sqlserver_auth.py
Labels: area:profile, size:L, lgtm

#1735 Re-enable integration tests durations to troubleshoot performance degradation
  scripts/test/integration.sh
Labels: area:performance, area:testing, size:XS

#1743 Run listener tests in Airflow 3
  cosmos/listeners/dag_run_listener.py
  tests/listeners/test_dag_run_listener.py
Labels: area:testing, size:M, lgtm

#1738 Fix `full_refresh` parameter in `AIRFLOW_ASYNC` execution config mode
  cosmos/operators/_asynchronous/bigquery.py
  cosmos/operators/airflow_async.py
  cosmos/operators/local.py
  dev/dags/simple_dag_async.py
  tests/operators/_asynchronous/test_bigquery.py
  tests/operators/test_local.py
Labels: area:execution, dbt:run, size:M, lgtm

#1749 Fix dbt ls invocation method log message
  cosmos/dbt/graph.py
Labels: area:logging, dbt:list, size:XS

#1755 Add Airflow3 db files to ignore from git tracking
  .gitignore
Labels: size:XS, lgtm

#1740 Ensure remote target directory are created when copying files when using local directory
  cosmos/operators/local.py
  tests/operators/test_local.py
Labels: execution:local, size:S, lgtm

#1768 Support custom `packages-install-path`
  cosmos/constants.py
  cosmos/dbt/project.py
  tests/dbt/test_project.py
Labels: area:dependencies, dbt:deps, size:M

#1764 Log contents of `packages.yml` when `AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG`
  cosmos/operators/local.py
Labels: area:logging, size:S

#1760 Disable dbt static parser during Airflow task execution using dbt runner
  cosmos/operators/local.py
  tests/operators/test_local.py
Labels: parsing:custom, execution:local, area:parsing, area:execution, size:M, lgtm

#1773 Fix Airflow dependencies in the CI
  scripts/test/pre-install-airflow.sh
Labels: area:dependencies, area:ci, size:M

#1772 Fix `ExecutionMode.LOCAL` to leverage `ProjectConfig.manifest_path`
  cosmos/converter.py
  cosmos/dbt/project.py
  cosmos/operators/local.py
  dev/dags/dbt/jaffle_shop/target/manifest.json
  docs/configuration/operator-args.rst
  tests/dbt/test_project.py
  tests/operators/test_local.py
Labels: parsing:dbt_manifest, execution:local, area:config, area:execution, size:M

#1741 Refactor `AIRFLOW_ASYNC` so that the path in the remote object store is specific per DAG run
  cosmos/operators/_asynchronous/__init__.py
  cosmos/operators/_asynchronous/bigquery.py
  cosmos/operators/local.py
  tests/operators/_asynchronous/test_base.py
  tests/operators/_asynchronous/test_bigquery.py
  tests/operators/test_local.py
  tests/operators/test_virtualenv.py
Labels: area:execution, area:testing, size:L, lgtm

#1775 Release 1.10.1 (add changelog and version bump)
  CHANGELOG.rst
  cosmos/__init__.py
Labels: area:docs, size:M

#1788 Fix `test_async_example_dag_without_setup_task` tests
  tests/test_example_dags.py
Labels: area:testing, size:XS
